### ISSUE TITLE
Fix text wrapping on subreddits

### ISSUE THREAD

**Issue by sambattalio** [wtheisen/commandChan#14]
### Issue and Steps to Reproduce

Looks as though the "buttons" were made for smaller 4chan boards, however some subreddits are fairly long.

What do you think we should do?

**To reproduce:**
`:reddit` and you should see how it wraps pretty bad.

### Version
latest from source

### Screenshots
<img width="923" alt="cchan" src="https://user-images.githubusercontent.com/6098588/61957391-2eaf4a00-af8d-11e9-949b-929d8cc5ba9b.png">

#### Expected
Probably some sort of custom sizing views? I don't know if this is something to fix but it looks kinda bad.

#### Actual

Wrap text if longer than 6 characters.

### Additional Details
* Installed packages:
Terminal: iterm2

**Comment by sambattalio** [comment]
@wtheisen what do you think about this?

**Comment by wtheisen** [comment]
Is there some way we could just have the size of the buttons scale to the size of the text? Or do you think that would look worse? Conversely another option would be to have a list instead of a grid of buttons.

**Comment by ginglis13** [comment]
Would this be something that gets changed w the treeview? Like are we going for a list view of subreddits/boards that expands to a tree view once you click for the comments/post?

**Comment by sambattalio** [comment]
> Would this be something that gets changed w the treeview? Like are we going for a list view of subreddits/boards that expands to a tree view once you click for the comments/post?

I was almost thinking of something like that. Because I figured at the very least I'd probably keep subreddits to match the style of the 4chan boards. But I was thinking tree view probably shouldn't kick in till you are actually on a post. Thoughts?

**Comment by wtheisen** [comment]
I personally think we should have reddit split up into three peices like the 4chan side. Subreddit Index, Subreddit, and specific post in order to keep down on the visual noise and levels of indentation. Changing the index and subreddit views to a list would probably make the most sense as we have the search command so it's relatively easy to jump around. We can also add more keybindings to allow larger jumps too.

**Comment by wtheisen** [comment]
so using an Urwid.Pile as the super-type

**Comment by sambattalio** [comment]
Sounds good to me. I agree with that. I can work on that with tree view if oyu want

**Comment by ginglis13** [comment]
Could also just make the boxes longer by default, and have less boxes per row. but I like @wtheisen 's idea

**Comment by sambattalio** [comment]
so subreddit index / posts are urwid.pile then individual posts are trees

**Comment by wtheisen** [comment]
I think getting the tree view for comments is the biggest thing right now. We can worry about pretty-formatting after getting the functionality in

**Comment by sambattalio** [comment]
alright gotcha, just htought i'd add this to have in mind. I'll keep it in mind while tree-ing

**Comment by wtheisen** [comment]
Doing a pile also makes sense for other sites like hackernews as that is how they are naturally displayed. The reason I did the box grid for 4chan is because that is what the site looks like in catalogue mode

**Comment by ginglis13** [comment]
Hey guys, looking into the text wrapping on the index view for reddit (and I guess this applies to chan, etc. as well). The [docs](http://urwid.org/reference/widget.html#urwid.Widget.pack) have this:

```
Text widgets have implemented this method. You can use Text.pack() to calculate the minimum columns and rows required to display a text widget without wrapping, or call it iteratively to calculate the minimum number of columns required to display the text wrapped into a target number of rows.
```

This might be our answer!

**Comment by sambattalio** [comment]
Thank you for the research! This is very helpful. I can look into this ASAP to provide a clean, and elegant index page for the reddit feature.

**Comment by ginglis13** [comment]
Of course! Not sure if this is the best option to go with, but I think we may be able to replace buttons with a custom widget that is selectable and uses the above approach
