### ISSUE TITLE
Feature Request: Testing

### ISSUE THREAD

**Issue by ginglis13** [wtheisen/commandChan#15]
Obviously something that is not urgent, but would be cool to make a suite of tests for commandChan. I especially would like to do this b/c I don't have much experience writing tests.

**Comment by wtheisen** [comment]
I know @sambattalio wanted testing as well. If he's going to cover the reddit/tree comment stuff then you're more than welcome to start writing tests!

**Comment by sambattalio** [comment]
Big brain moves making all these issues for the contribution points 🧠. If you want I have a general idea of unit testing and mocking I can probably whip together some resources to help out. I have used pytest in the past for some stuff/work. I think a good general method would be to make the basis and then just require EVERY new feature to have at least one test for it. Then we can start sweating on code coverage. I would strongly recommend using pytest though

**Comment by sambattalio** [comment]
It’s actually easier than it seems from my experience, it is just a pain to make tests for everything at first. But once we make a good system it really should be easy to add tests.

I think mocking would be really beneficial for this project so we can simulate the sites with expected inputs without depending on internet

**Comment by ginglis13** [comment]
Ok. Yea I was thinking of just adding some super basic initial tests, to be fleshed out later/as we get there

**Comment by wtheisen** [comment]
so could we just have some test json files in the config? like just save a snapshot of a currently live json data?

**Comment by sambattalio** [comment]
json files could be nice. I've had projects use json or others that just hardcode in stuff. But with the size of these responses I think having json files would be very nice with different possibilities (403,...)

**Comment by ginglis13** [comment]
couldn't we just update config from tests directly?

**Comment by sambattalio** [comment]
oh yea misread I thought he meant json files holding api call data

**Comment by sambattalio** [comment]
We would have a config object that we change values for testing cases

**Comment by ginglis13** [comment]
oic

**Comment by ginglis13** [comment]
Oh shoot i see. He means like the json response. not the config lol sorry

**Comment by wtheisen** [comment]
no I meant just having json files in the config folder or test folder or whatever. The files being snapshots of live requests that we can just re-use to test in the future

**Comment by sambattalio** [comment]
I think ideally we would just have tests/ and src/ in our root directory. And in tests/ we could have like reddit/inputs/xxx.json or something with files and reddit/test_post.py

**Comment by sambattalio** [comment]
Then we can REALLY dig into CI and making sure PR's pass / make tests before accepting

**Comment by wtheisen** [comment]
yeah okay that's what I was thinking as well

**Comment by wtheisen** [comment]
I also will not be contributing to tests at any point :chad: that's on you guys

**Comment by ginglis13** [comment]
Hi @sambattalio @wtheisen - want to confirm the structure of the projecs w/ tests. Def making a tests/ dir, should I also throw existing code into a src/ dir?

**Comment by ginglis13** [comment]
I been had been looking at this - correct me if wrong bc am nub, but will doing this mean we have to change all imports of custom classes/files? seems like you have to append `src.` to each import, like `from src.debug import DEBUG` in `src/config.py`. Not sure if this is what our dear leader intends

**Comment by wtheisen** [comment]
I suppose it’ll need to be done at some point right

**Comment by ginglis13** [comment]
Ok. I will keep looking into it - another note, seems like urwid itself uses the `unittest` module, not `pytest`
