### ISSUE TITLE
Readme Out of Date

### ISSUE THREAD

**Issue by sambattalio** [wtheisen/commandChan#20]
### Issue and Steps to Reproduce
The Readme is out of date for the current architecture/state of the project. Probably needs to be updated at some point.

### Version
Source
### Screenshots
https://github.com/wtheisen/commandChan/blob/master/README.md
#### Expected
Probably an updated readme
#### Actual
Out of date readme

**Comment by wtheisen** [comment]
Also we should add some screenshots of the reddit-mode, right now we don't really demonstrate that you can browse reddit too!

**Comment by wtheisen** [comment]
Done
