### ISSUE TITLE
Implement travis-ci with pytest

### ISSUE THREAD

**Issue by ginglis13** [wtheisen/commandChan#21]
### Issue and Steps to Reproduce

Gotta add that CI ya know.

### Version
v2

#### Expected

automatic running of tests w/ pytest

**Comment by sambattalio** [comment]
This is definitely something that should be fairly easy after we get "decent" code coverage.

**Comment by ginglis13** [comment]
Yup. I also think we should edit our PR template to reference existing or new tests

**Comment by sambattalio** [comment]
If you need help w/ ci lmk

**Comment by ginglis13** [comment]
sure yea. I saw an example travis.yml that was super straight forward. All it did was declare the python env, and call pytest. I figure I'll just do something like that

**Comment by sambattalio** [comment]
facts thats basically it lol. It can get really neat for other projects with multiple jobs and CD
