### ISSUE TITLE
Displaying updates on the welcome screen

### ISSUE THREAD

**Issue by wtheisen** [wtheisen/commandChan#35]
It would be cool if the welcome screen also showed the last 3ish updates to the repo, neat little feature and probably pretty easy.

**Comment by ginglis13** [comment]
Would it make sense then to start a changelog.md or something? We can get into a habit of adding to this file every PR/change, and include adding changes/fixes to this file in the PR template.

**Comment by wtheisen** [comment]
I was thinking that’s something we could pull automatically. I wouldn’t want to have to manually record everything

**Comment by ginglis13** [comment]
Ok yea that would prolly be a bit tedious to do manually. Where were you thinking it would pull from?

**Comment by wtheisen** [comment]
I’m just assuming there’s some kind of github api we could make use of

**Comment by ginglis13** [comment]
So just like commit messages?

**Comment by wtheisen** [comment]
Yeah something to that effect

**Comment by sambattalio** [comment]
GitHub api is nice, but we have to be careful about that, because it _might_ need an api key which could be interesting to work with

**Comment by ginglis13** [comment]
Yea I think I'll look into this. Commit message is definitely an option, and maybe we can even get the description from a pull request? Idk, just spit-balling.

**Comment by wtheisen** [comment]
https://api.github.com/repos/wtheisen/commandChan/commits/master

**Comment by wtheisen** [comment]
Managed to figure out the correct endpoint to pull from! This will make it really easy to add this cool little feature!

**Comment by sambattalio** [comment]
Great find @wtheisen! Glad to see it didn't need any api keys
